#!/bin/bash

echo "Création d'une sauvegarde"


echo "----------------------------------"




dossier_existe=false






while [ "$dossier_existe" = false ]; do


    echo "Veuillez spécifier le dossier que vous souhaitez sauvegarder :"


    read dossier




    


    if ls "$dossier" >/dev/null 2>&1; then


        echo "Le dossier $dossier va être sauvegardé."


        dossier_existe=true


    else


        echo "Le dossier spécifié n'existe pas. Veuillez entrer un dossier valide."


    fi






echo "Veuillez spécifier l'endroit où sauvegarder le dossier :"


read destination






read -p "Confirmez-vous la sauvegarde du dossier '$dossier' à l'emplacement '$destination' ? (oui/non) : " confirmation




if [ "$confirmation" != "oui" ]; then


    echo "La sauvegarde a été annulée."


    exit 1


fi




echo "La sauvegarde du dossier $dossier à l'emplacement $destination est en cours..."




{


    if [ ! -d "$destination" ]; then


        echo "Le dossier de destination n'existe pas. Création en cours..."


        mkdir -p "$destination"


    fi


}






cp -r "$dossier" "$destination"




if [ $? -eq 0 ]; then


    echo "La sauvegarde a été correctement effectuée."


else


    echo "Une erreur s'est produite lors de la sauvegarde."


fi




read -p "Voulez-vous sauvegarder un autre dossier ? (oui/non) : " autre_sauvegarde




if [ "$autre_sauvegarde" != "oui" ]; then


    exit 0


fi


done

